CREATE TABLE Banks_Payments(
    SWIFT_ID TEXT PRIMARY KEY NOT NULL,
    BANK_NAME TEXT NOT NULL
);

CREATE TABLE Companies_Payments(
    COMPANY_ID BIGINT PRIMARY KEY NOT NULL,
    COMPANY_NAME TEXT NOT NULL,
    COMPANY_CURRENCY TEXT NOT NULL
);

CREATE TABLE Users_Payments(
    USER_NAME TEXT NOT NULL,
    USER_ID BIGINT NOT NULL ,
    COMPANY_ID BIGINT NOT NULL, 
    USER_PASSWORD TEXT NOT NULL,
    USER_GENDER TEXT NOT NULL,
    CONSTRAINT fk_company_id
        FOREIGN KEY(COMPANY_ID)
            REFERENCES Companies_Payments(COMPANY_ID),
    PRIMARY KEY (USER_ID,COMPANY_ID)
);

CREATE TABLE Debit_Accounts_Payments(
    DEBIT_ACCOUNT_ID BIGINT PRIMARY KEY NOT NULL,
    DEBIT_ACCOUNT_NUMBER BIGINT NOT NULL,
    DEBIT_ACCOUNT_CURRENCY TEXT NOT NULL,
    DEBIT_BANK TEXT NOT NULL,
    DEBIT_ACCOUNT_BALANCE INT NOT NULL,

    COMPANY_ID BIGINT NOT NULL,

    CONSTRAINT fk_company_id
        FOREIGN KEY(COMPANY_ID)
            REFERENCES Companies_Payments(COMPANY_ID)
);

CREATE TABLE Credit_Accounts_Payments(
    PAYEE_NAME TEXT NOT NULL,
    CREDIT_ACCOUNT_NUMBER BIGINT NOT NULL,
    SWIFT_ID TEXT NOT NULL,
    IS_SAVED BOOLEAN NOT NULL,
    NICKNAME TEXT,
    CONSTRAINT fk_swift
        FOREIGN KEY(SWIFT_ID)
            REFERENCES Banks_Payments(SWIFT_ID),
    PRIMARY KEY (CREDIT_ACCOUNT_NUMBER)


);

CREATE TABLE Transaction_Payments(
    REFERENCE_NUMBER BIGINT PRIMARY KEY NOT NULL,
    DATE_OF_TRANSFER DATE NOT NULL,
    AMOUNT INT NOT NULL,
    TRANSFER_CURRENCY TEXT NOT NULL,
    EQUIVALENT_AMOUNT INT NOT NULL,
    COMMENTS TEXT NOT NULL,
    T_STATUS TEXT NOT NULL,
    COMPANY_ID BIGINT NOT NULL,
    USER_ID BIGINT NOT NULL,
    DEBIT_ACCOUNT_ID BIGINT NOT NULL,
    CREDIT_ACCOUNT_NUMBER BIGINT NOT NULL,
    SWIFT_ID TEXT NOT NULL,

    CONSTRAINT fk_company_user_id
        FOREIGN KEY(USER_ID,COMPANY_ID)
            REFERENCES Users_Payments(USER_ID,COMPANY_ID),

    CONSTRAINT fk_debit_ac
        FOREIGN KEY(DEBIT_ACCOUNT_ID)
            REFERENCES Debit_Accounts_Payments(DEBIT_ACCOUNT_ID),
    CONSTRAINT fk_credit_ac
         FOREIGN KEY(CREDIT_ACCOUNT_NUMBER)
             REFERENCES Credit_Accounts_Payments(CREDIT_ACCOUNT_NUMBER),

    CONSTRAINT fk_credit_swift
        FOREIGN KEY(SWIFT_ID)
            REFERENCES Banks_Payments(SWIFT_ID)
	
    -- CONSTRAINT fk_currency_convert
    --     FOREIGN KEY(TRANSFER_CURRENCY)
    --         REFERENCES Currency_Conversion_Payments(TO_CURRENCY)
);





